engines:
 duplication:
   enabled: true
   config:
     languages:
     - python
 pep8:
   enabled: false
 radon:
   enabled: true
   config:
     threshold: "C"
 eslint:
   enabled: false
 shellcheck:
   enabled: false
 csslint:
   enabled: false

ratings:
 paths:
 - "**.py"
 - "**.js"
 - "**.sh"
 - "**.css"

exclude_paths:
