language: python

dist: xenial

services:
  - docker

addons:
    apt:
        packages:
            - libxkbcommon-x11-0  # for PyQt 5.12

matrix:
    include:
        # remove when we create redirects for old doc on our servers
        - env: BUILD_DOCS=true
          python: '3.6'
          script: source $TRAVIS_BUILD_DIR/.travis/build_doc.sh
    fast_finish: true

cache:
    apt: true
    pip: true
    ccache: true
    directories:
        - $TRAVIS_BUILD_DIR/postgres
        - $TRAVIS_BUILD_DIR/pyqt

before_cache:

before_install:
    - set -e  # fail on any error
    - source $TRAVIS_BUILD_DIR/.travis/util.sh

install:
    - source $TRAVIS_BUILD_DIR/.travis/stage_install.sh

script:
    - source $TRAVIS_BUILD_DIR/.travis/stage_script.sh

after_success:
    - source $TRAVIS_BUILD_DIR/.travis/stage_after_success.sh
